const customers = [
  {
    id: 1,
    image: "imgs/img1.png",
    firstname: "Joseph ",
    lastname: "Ike",
    location: "In Ikeja",
    category: "customer",
    text: "vero, delectus ullam.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum, fuga. Excepturi aliquam ex culpa, eius atque vero. Harum quod quam magnam nesciunt debitis veniam. Quos reprehenderit asperiores ipsa inventore ",
  },
  {
    id: 2,
    image: "imgs/img2.png",
    firstname: "Adetola ",
    lastname: "Fashina",
    location: "Ibadan",
    category: "customer",
    text: "vero, delectus ullam.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum, fuga. Excepturi aliquam ex culpa, eius atque vero. Harum quod quam magnam nesciunt debitis veniam. Quos reprehenderit asperiores ipsa inventore ",
  },
  {
    id: 3,
    image: "imgs/img3.png",
    firstname: "Emmanuel ",
    lastname: "Fayemi",
    location: "In lagos",
    category: "customer",
    text: "vero, delectus ullam.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum, fuga. Excepturi aliquam ex culpa, eius atque vero. Harum quod quam magnam nesciunt debitis veniam. Quos reprehenderit asperiores ipsa inventore ",
  },
  {
    id: 4,
    image: "imgs/img4.png",
    firstname: "Chisom ",
    lastname: "Obilor",
    location: "In Magode",
    category: "Vendor",
    text: "vero, delectus ullam.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum, fuga. Excepturi aliquam ex culpa, eius atque vero. Harum quod quam magnam nesciunt debitis veniam. Quos reprehenderit asperiores ipsa inventore ",
  },
  {
    id: 5,
    image: "imgs/img5.png",
    firstname: "Adunoluwa ",
    lastname: "Adeyemi",
    location: "Iwo Road",
    category: "Vendor",
    text: "vero, delectus ullam.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum, fuga. Excepturi aliquam ex culpa, eius atque vero. Harum quod quam magnam nesciunt debitis veniam. Quos reprehenderit asperiores ipsa inventore ",
  },
  {
    id: 6,
    image: "imgs/img6.png",
    firstname: "chidi ",
    lastname: "Okeke",
    location: "In Somolu",
    category: "Vendor",
    text: "vero, delectus ullam.Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum, fuga. Excepturi aliquam ex culpa, eius atque vero. Harum quod quam magnam nesciunt debitis veniam. Quos reprehenderit asperiores ipsa inventore ",
  },
];

export default customers;
